arm_id:                           $(arg arm_id)
singularity_warning_threshold:    0.0001               # print a warning if the smallest singular value of J x J^T drops below this value (use -1 to disable)
tau_ext_lowpass_filter:           1.0                  # Exponential Moving average filter: range between and zero (infinite delay) one (no filtering)

# Motion generators PID gains
motion_generators:
  position:
    gains:
      $(arg arm_id)_joint1: { p: 600, d: 30, i: 0 }
      $(arg arm_id)_joint2: { p: 600, d: 30, i: 0 }
      $(arg arm_id)_joint3: { p: 600, d: 30, i: 0 }
      $(arg arm_id)_joint4: { p: 600, d: 30, i: 0 }
      $(arg arm_id)_joint5: { p: 250, d: 10, i: 0 }
      $(arg arm_id)_joint6: { p: 150, d: 10, i: 0 }
      $(arg arm_id)_joint7: { p:  50, d:  5, i: 0 }
  velocity:
    gains:
      $(arg arm_id)_joint1: { p:  30, d:  0, i: 0 }
      $(arg arm_id)_joint2: { p:  30, d:  0, i: 0 }
      $(arg arm_id)_joint3: { p:  30, d:  0, i: 0 }
      $(arg arm_id)_joint4: { p:  30, d:  0, i: 0 }
      $(arg arm_id)_joint5: { p:  10, d:  0, i: 0 }
      $(arg arm_id)_joint6: { p:  10, d:  0, i: 0 }
      $(arg arm_id)_joint7: { p:   5, d:  0, i: 0 }

joint_names:
  - $(arg arm_id)_joint1
  - $(arg arm_id)_joint2
  - $(arg arm_id)_joint3
  - $(arg arm_id)_joint4
  - $(arg arm_id)_joint5
  - $(arg arm_id)_joint6
  - $(arg arm_id)_joint7

# Configure the threshold angle for printing joint limit warnings.
joint_limit_warning_threshold: 0.1 # [rad]
# Activate rate limiter? [true|false]
rate_limiting: true
# Cutoff frequency of the low-pass filter. Set to >= 1000 to deactivate.
cutoff_frequency: 100
# Internal controller for motion generators [joint_impedance|cartesian_impedance]
internal_controller: joint_impedance
# Used to decide whether to enforce realtime mode [enforce|ignore]
realtime_config: ignore
# Configure the initial defaults for the collision behavior reflexes.
collision_config:
  lower_torque_thresholds_acceleration: [20.0, 20.0, 18.0, 18.0, 16.0, 14.0, 12.0]  # [Nm]
  upper_torque_thresholds_acceleration: [20.0, 20.0, 18.0, 18.0, 16.0, 14.0, 12.0]  # [Nm]
  lower_torque_thresholds_nominal: [20.0, 20.0, 18.0, 18.0, 16.0, 14.0, 12.0]  # [Nm]
  upper_torque_thresholds_nominal: [20.0, 20.0, 18.0, 18.0, 16.0, 14.0, 12.0]  # [Nm]
  lower_force_thresholds_acceleration: [20.0, 20.0, 20.0, 25.0, 25.0, 25.0]  # [N, N, N, Nm, Nm, Nm]
  upper_force_thresholds_acceleration: [20.0, 20.0, 20.0, 25.0, 25.0, 25.0]  # [N, N, N, Nm, Nm, Nm]
  lower_force_thresholds_nominal: [20.0, 20.0, 20.0, 25.0, 25.0, 25.0]  # [N, N, N, Nm, Nm, Nm]
  upper_force_thresholds_nominal: [20.0, 20.0, 20.0, 25.0, 25.0, 25.0]  # [N, N, N, Nm, Nm, Nm]

